# Basic CI Pipeline
# Run tests on every push and pull request

name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run CI pipeline
        uses: spanscale/node-github-action@v1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}